"""Core HDC primitives: hypervector encoders and an OnlineHD-style classifier.

Implements the two encoding schemes considered in the MicroHD paper
(Ponzina & Rosing, tinyML'24):
  * ID-level encoding  (Rahimi et al., 2016)
  * non-linear projection encoding (Thomas et al., 2021)

and the retraining-based training procedure used by MicroHD
(single-pass accumulation + ep epochs of error-driven updates, lr=1).
"""

from __future__ import annotations

import math
from dataclasses import dataclass, replace

import torch
import torch.nn.functional as F

def resolve_device(device: str | None = None) -> torch.device:
    if device is not None:
        return torch.device(device)
    return torch.device("cuda" if torch.cuda.is_available() else "cpu")

def bipolar_sign(t: torch.Tensor) -> torch.Tensor:
    """Elementwise sign mapping to {-1,+1} with zeros mapped to +1."""
    return torch.where(t >= 0, 1.0, -1.0)

def rand_bipolar(*shape: int, generator: torch.Generator | None = None) -> torch.Tensor:
    """Uniform random bipolar hypervector."""
    return torch.where(torch.rand(shape, generator=generator) < 0.5, -1.0, 1.0)

@dataclass(frozen=True)
class HDCConfig:
    """HDC model hyper-parameters (Sec. 4 of the MicroHD paper).

    Attributes:
        encoding: "id" for ID-level encoding or "proj" for non-linear projection.
        dim: hyperspace dimensionality d (baseline 10_000).
        levels: number of level HVs l (ID-level only; baseline 1024).
        quant_bits: bitwidth q for class HVs and the projection matrix (baseline 16).
    """

    encoding: str
    dim: int = 10_000
    levels: int = 1024
    quant_bits: int = 16

    def __post_init__(self) -> None:
        if self.encoding not in ("id", "proj"):
            raise ValueError(self.encoding)

    def with_(self, **overrides) -> "HDCConfig":
        return replace(self, **overrides)

def uniform_quantize(t: torch.Tensor, bits: int) -> torch.Tensor:
    """Symmetric uniform quantization over the observed max magnitude."""
    if bits >= 31:
        return t
    levels = 2 ** (bits - 1) - 1
    delta = t.abs().max().clamp_min(1e-12) / levels
    return torch.round(t / delta).clamp(-levels, levels) * delta

class IDEncoder:
    """ID-level encoder: per-feature random base HVs bound with level HVs.

    Level HVs are generated by iteratively flipping a fraction rho of bits,
    with rho chosen so that first and last levels are quasi-orthogonal
    (expected cosine similarity ~0), preserving similarity between nearby
    feature values.
    """

    def __init__(
        self,
        num_features: int,
        dim: int,
        num_levels: int,
        *,
        seed: int = 0,
        device: str | None = None,
    ) -> None:
        self.num_features = num_features
        self.dim = dim
        self.num_levels = num_levels
        self.device = resolve_device(device)
        g = torch.Generator().manual_seed(seed)

        self.base_hvs = rand_bipolar(num_features, dim, generator=g)
        self.level_hvs = self._build_levels(num_levels, dim, g)
        self._feat_min: torch.Tensor | None = None
        self._feat_max: torch.Tensor | None = None

    @staticmethod
    def _build_levels(num_levels: int, dim: int, g: torch.Generator) -> torch.Tensor:
        if num_levels <= 1:
            return torch.ones(1, dim)
        # Per-step flip prob chosen so first/last levels are quasi-orthogonal:
        # E[sim(L_0, L_{L-1})] = (1-2*rho)^(L-1) ~= EPS_ENDPOINT.
        eps_endpoint = 0.05
        rho = (1.0 - eps_endpoint ** (1.0 / (num_levels - 1))) / 2.0
        rows = []
        v = rand_bipolar(dim, generator=g)
        rows.append(v)
        for _ in range(num_levels - 1):
            flip = torch.rand(dim, generator=g) < rho
            v = torch.where(flip, -v, v)
            rows.append(v.clone())
        return torch.stack(rows)

    def fit_feature_range(self, x: torch.Tensor) -> None:
        x = x.to(self.device)
        self._feat_min = x.min(dim=0).values
        self._feat_max = x.max(dim=0).values

    @torch.no_grad()
    def encode(self, x: torch.Tensor) -> torch.Tensor:
        """Encode (n, f) float inputs into (n, d) bipolar hypervectors."""
        assert self._feat_min is not None, "call fit_feature_range first"
        x = x.to(self.device)
        span = (self._feat_max - self._feat_min).clamp_min(1e-12)
        xn = ((x - self._feat_min) / span).clamp(0.0, 1.0)
        idx = torch.round(xn * (self.num_levels - 1)).long()  # (n, f)

        n = x.shape[0]
        out = torch.zeros(n, self.dim, device=self.device)
        base = self.base_hvs.to(self.device)
        levels = self.level_hvs.to(self.device)
        for f in range(self.num_features):
            lv = levels.index_select(0, idx[:, f])  # (n, d)
            out += lv * base[f]
        return bipolar_sign(out)

class ProjectionEncoder:
    """Non-linear projection encoder: sign(x @ P^T).

    P is drawn i.i.d. N(0, 1/f). When `quant_bits < 16` the stored matrix is
    quantized uniformly over its range before use (MicroHD co-optimizes q).
    """

    def __init__(
        self,
        num_features: int,
        dim: int,
        *,
        seed: int = 0,
        quant_bits: int = 16,
        device: str | None = None,
    ) -> None:
        self.num_features = num_features
        self.dim = dim
        self.quant_bits = quant_bits
        self.device = resolve_device(device)
        g = torch.Generator().manual_seed(seed)
        P = torch.randn(dim, num_features, generator=g) / math.sqrt(num_features)
        self.proj = uniform_quantize(P, quant_bits).to(self.device)

    def fit_feature_range(self, x: torch.Tensor) -> None:
        """No-op; kept for API parity with IDEncoder."""

    @torch.no_grad()
    def encode(self, x: torch.Tensor) -> torch.Tensor:
        return bipolar_sign(x.to(self.device) @ self.proj.T)

class HDClassifier:
    """Class-HV classifier trained like OnlineHD / MicroHD.

    Training = single pass accumulation followed by `epochs` error-driven
    retraining passes with learning rate lr (paper: lr=1, ep=30).
    Class HVs are integer accumulations; at inference time they can be
    deployed at reduced bitwidth q via `deploy_bits`.
    """

    def __init__(self, encoder, num_classes: int, *, device: str | None = None) -> None:
        self.encoder = encoder
        self.num_classes = num_classes
        self.device = encoder.device
        self.class_hvs = torch.zeros(
            num_classes, encoder.dim, dtype=torch.float32, device=self.device
        )

    def _encode_cache(self, x: torch.Tensor, batch_size: int) -> torch.Tensor:
        n = x.shape[0]
        cache = torch.empty(n, self.encoder.dim, dtype=torch.int8, device=self.device)
        for i in range(0, n, batch_size):
            cache[i : i + batch_size] = (
                self.encoder.encode(x[i : i + batch_size]).to(torch.int8)
            )
        return cache

    @staticmethod
    def _batches(n: int, batch_size: int, shuffle: bool, generator=None):
        idx = torch.randperm(n, generator=generator) if shuffle else torch.arange(n)
        for i in range(0, n, batch_size):
            yield idx[i : i + batch_size]

    @torch.no_grad()
    def fit(
        self,
        x: torch.Tensor,
        y: torch.Tensor,
        *,
        epochs: int = 30,
        lr: float = 1.0,
        batch_size: int = 2048,
        seed: int = 0,
    ) -> "HDClassifier":
        x = x.detach().to(self.device, torch.float32)
        y = y.detach().to(self.device, torch.long)
        n = x.shape[0]
        enc = self._encode_cache(x, batch_size)

        g = torch.Generator().manual_seed(seed)
        self.class_hvs.zero_()
        for b in self._batches(n, batch_size, shuffle=False):
            hb = enc[b].to(torch.float32)
            self.class_hvs.index_add_(0, y[b], hb)

        cn = F.normalize(self.class_hvs, dim=1)
        for _ in range(epochs):
            for b in self._batches(n, batch_size, shuffle=True, generator=g):
                xb, yb = enc[b].to(torch.float32), y[b]
                scores = xb @ cn.T
                pred = scores.argmax(dim=1)
                wrong = pred != yb
                if wrong.any():
                    hw = lr * xb[wrong]
                    self.class_hvs.index_add_(0, yb[wrong], hw)
                    self.class_hvs.index_add_(0, pred[wrong], -hw)
                    cn = F.normalize(self.class_hvs, dim=1)
        return self

    def class_hvs_at_bits(self, bits: int) -> torch.Tensor:
        return uniform_quantize(self.class_hvs, bits)

    @torch.no_grad()
    def scores(
        self,
        x: torch.Tensor,
        *,
        deploy_bits: int | None = None,
        batch_size: int = 4096,
    ) -> torch.Tensor:
        c = self.class_hvs if deploy_bits is None else self.class_hvs_at_bits(deploy_bits)
        cn = F.normalize(c, dim=1)
        outs = []
        for i in range(0, x.shape[0], batch_size):
            outs.append(self.encoder.encode(x[i : i + batch_size]) @ cn.T)
        return torch.cat(outs, dim=0)

    def predict(self, x: torch.Tensor, **kw) -> torch.Tensor:
        return self.scores(x, **kw).argmax(dim=1)

def build_encoder(cfg: HDCConfig, num_features: int, *, seed: int = 0, device=None):
    if cfg.encoding == "id":
        return IDEncoder(num_features, cfg.dim, cfg.levels, seed=seed, device=device)
    return ProjectionEncoder(
        num_features, cfg.dim, seed=seed, quant_bits=cfg.quant_bits, device=device
    )
